### ISSUE TITLE
Possible duplicate in OpenAPI YAML examples?

### ISSUE THREAD

**Issue by arnatal** [CloudNativeSDWAN/cnwan-reader#14]
Is this example supposed to have a duplicate key-value pair?

https://github.com/CloudNativeSDWAN/cnwan-reader/blob/6fa8768d654fa812e077aebbdbd1a54fb05d0d4a/api/openapi.yaml#L145

Same with the one below

https://github.com/CloudNativeSDWAN/cnwan-reader/blob/6fa8768d654fa812e077aebbdbd1a54fb05d0d4a/api/openapi.yaml#L171

**Comment by SunSince90** [comment]
Copy-paste problem. Thank you!

**Comment by SunSince90** [comment]
Fixed by #15
