### ISSUE TITLE
Support for etcd

### ISSUE THREAD

**Issue by SunSince90** [CloudNativeSDWAN/cnwan-reader#18]
The reader will be update to provide support for etcd: it will be able to watch for changes to Namespaces, Services and Endpoints according to a prefix and credentials.

- [x] Create the command
- [x] Create and parse flags 
- [x] Establish connection to etcd
- [x] Observe current state of the cluster for initial send
- [x] Watch events
  - [x] Process a create event
  - [x] Process an update event
  - [x] Process a delete event
- [x] Unit tests
- [x] Update configuration file to include etcd settings
- [ ] Update version command
- [ ] Update documentation on use with etcd
- [ ] Update changelog

**Comment by SunSince90** [comment]
Updating list to include configuration map

**Comment by ljakab** [comment]
Is the progress tracking list up to date, or have been progressing more since last time you revisited this issue?

**Comment by SunSince90** [comment]
No updates, the existing PR depends on some packages that have been created with the operator
